// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zdhzxwuwkfsibmtfpjgh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpkaHp4d3V3a2ZzaWJtdGZwamdoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYyMzQ3MTksImV4cCI6MjA2MTgxMDcxOX0.rPdnUbAZALVDgGJGXjdbRntT971bxkgOE7FLOhx9S_k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);